return {
    -- "nvim-neo-tree/neo-tree.nvim",
    -- opts = {
    --     reveal = true,
    --     source_selector = {
    --         winbar = false,
    --         statusline = false
    --     },
    --     default_component_configs = {
    --         name = {
    --             use_git_status_colors = false
    --         }
    --     }
    -- },
    -- branch = "v3.x",
    -- dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
    --     "MunifTanjim/nui.nvim",
    -- }
}
